name: Create PR for foundations-documentation

on:
  release:
    types: [published, edited]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install depedencies
        run: npm install
      - name: Run script
        run: echo $GITHUB_REF

